version: 6.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
configuration: Debug
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src\Shapeshifter.sln
build:
  project: src\Shapeshifter.sln
  verbosity: normal
artifacts:
- path: build\application\Shapeshifter.exe
  name: Deployment
deploy:
- provider: GitHub
  release: shapeshifter-v$(appveyor_build_version)
  auth_token:
    secure: bEEQPxNCa8Kb1CYtJddx0wPImmY2T/ZCrXVFf+RVtEC0Lvb0pVDE2D6sjfy9NxdV
  on:
    branch: master
test_script:
  - nuget install opencover -ExcludeVersion -OutputDirectory %APPVEYOR_BUILD_FOLDER%\tools

    %APPVEYOR_BUILD_FOLDER%\tools\OpenCover\tools\OpenCover.Console.exe -output:"coverage.xml" -target:"vstest.console.exe" -targetargs:"/logger:Appveyor \"%APPVEYOR_BUILD_FOLDER%\build\tests\Shapeshifter.Tests.dll\"" -excludebyattribute:*ExcludeFromCodeCoverage* -register:user -skipautoprops -returntargetcode

    C:\Python35-x64\python.exe -m pip install codecov

    C:\Python35-x64\Scripts\codecov -f coverage.xml
